#!/bin/bash

if [ ! $(whoami) = "root" ]
then
    dialog --title "root" --msgbox "You need root" 0 0
    clear
    exit
fi

dialog --title "Alert" --yesno "this script is a thorough cleaning, recommended: read very well, what the script is doing. Continue?" 0 0
if [ ! $? = 0 ]
then
    clear
    exit
fi

dialog --title "tmp" --yesno "Clean temps folder (thumbnails, tmp directory, etc)" 0 0
if [ $? = 0 ]
then
    rm -vfr /tmp/*
    rm -vfr /var/tmp/*
    rm -vfr ~/.cache/thumbnails/*
    rm -vfr ~/.thumbs/*
fi
dialog --title "trash" --yesno "Clean trash?" 0 0
if [ $? = 0 ]
then
    rm -vfr ~/.local/share/Trash/*
fi

#gestor de paquetes
if [ -f "/usr/bin/zypper" ] || [ -f "/usr/sbin/zypper" ] || [ -f "/usr/games/zypper" ]
then
    dialog --title "zypper" --yesno "Update from zypper?" 0 0
    if [ $? = 0 ]
    then
        zypper ref
        zypper up
    fi
    dialog --title "zypper" --yesno "remove unnecessary packages from zypper?" 0 0
    if [ $? = 0 ]
    then
        zypper packages --unneeded | awk -F'|' 'NR==0 || NR==1 || NR==2 || NR==3 || NR==4 {next} {print $3}' | grep -v Name | sudo xargs zypper remove --clean-deps
        zypper cc
    fi
fi
if [ -f "/usr/bin/apt" ] || [ -f "/usr/sbin/apt" ] || [ -f "/usr/games/apt" ]
then
    dialog --title "apt" --yesno "Update from apt?" 0 0
    if [ $? = 0 ]
    then
        apt update
        apt upgrade
    fi
    dialog --title "apt" --yesno "remove unnecessary packages from apt?" 0 0
    if [ $? = 0 ]
    then
        apt autoremove
        apt autoclean
        apt clean
    fi
fi
if [ -f "/usr/bin/dnf" ] || [ -f "/usr/sbin/dnf" ] || [ -f "/usr/games/dnf" ]
then
    dialog --title "dnf" --yesno "Update from dnf?" 0 0
    if [ $? = 0 ]
    then
        dnf upgrade --refresh
    fi
    dialog --title "dnf" --yesno "remove unnecessary packages from dnf?" 0 0
    if [ $? = 0 ]
    then
        dnf autoremove
        dnf clean all
    fi
fi
if [ -f "/usr/bin/pacman" ] || [ -f "/usr/sbin/pacman" ] || [ -f "/usr/games/pacman" ]
then
    dialog --title "pacman" --yesno "Update from pacman?" 0 0
    if [ $? = 0 ]
    then
        pacman -Syu
    fi
    dialog --title "pacman" --yesno "remove unnecessary packages from pacman?" 0 0
    if [ $? = 0 ]
    then
        pacman -Rs $(pacman -Qtdq)
    fi
fi
if [ -f "/usr/bin/eopkg" ] || [ -f "/usr/sbin/eopkg" ] || [ -f "/usr/games/eopkg" ]
then
    dialog --title "eopkg" --yesno "Update from eopkg?" 0 0
    if [ $? = 0 ]
    then
        eopkg upgrade
    fi
fi



if [ -f "/usr/bin/snap" ] || [ -f "/usr/sbin/snap" ] || [ -f "/usr/games/snap" ]
then
    dialog --title "snap" --yesno "Update snap?" 0 0
    if [ $? = 0 ]
    then
        snap refresh
    fi
fi
if [ -f "/usr/bin/flatpak" ] || [ -f "/usr/sbin/flatpak" ] || [ -f "/usr/games/flatpak" ]
then
    dialog --title "flatpak" --yesno "Update flatpak?" 0 0
    if [ $? = 0 ]
    then
        flatpak update
    fi
fi
clear
