#!/usr/bin/bash
if [ ! $(whoami) = "root" ]
then
    if [ -f "/usr/bin/dialog" ] || [ -f "/usr/sbin/dialog" ] || [ -f "/usr/games/dialog" ]
    then
        dialog --title "root" --msgbox "You need run this script as root" 0 0
    else
        echo "You need run this script as root"
    fi
    clear
    exit
fi

echo "remove tcs-cleaner if it's installed"
rm -vrf /usr/bin/tcs-cleaner
rm -vrf /usr/bin/tcs-cleaner-remove

rm -vrf /usr/share/applications/tcs-cleaner*
rm -vrf /usr/share/icons/hicolor/256x256/apps/tcs-cleaner.png
